Suqare button  component
TablaHR/tabla-atelier pull request #8
Opened 2021-06-02 18:31 UTC by raphaelwho

Added a button component

2021-06-02 19:13 UTC, ahamilton454 commented on client/components/related/Box.jsx
> +    let content ={
Since this CSS is not inheriting anything from the component's props, I would suggest moving this into a css file and using the .mask {} selector rather than adding it directly to the tag.

2021-06-02 19:16 UTC, ahamilton454 commented on client/components/related/Card.jsx
> +  componentDidMount() {
Ajax requests like this should probably be written in a helper file and imported since they will likely clutter the Card.jsx component.  We can check this component out more at later today though since I want to actually see it in action.

2021-06-02 19:19 UTC, ahamilton454 commented on client/components/shared/Square_button/Square_button.jsx
> +import React, { Component } from 'react'
I would probably create a generic button component with multiple enumeration rather than just create square button.

2021-06-02 19:19 UTC, ahamilton454 commented on client/index.jsx
> +import Square_button from './components/shared/Square_button/Square_button.jsx'
I do not think you need the subfolder Square_button to house one component, Square_button.jsx.

2021-06-02 19:21 UTC, ahamilton454 reviewed
Good code, I think it needs a bit of refactoring for organizational purposes, but then its ready.  I want to have someone else in the group also review my comments to see if they agree of disagree with what I had to say.  Also I used github commenting incorrectly, so you will need to look at the commits themselves with the comment (sorry for the mistake).

2021-06-02 19:55 UTC, raphaelwho commented on client/components/related/Box.jsx
> +    let content ={
this floating box need to be toggle so, adding in the reader function is necessary, we could talk about later, if we have some better solution.

2021-06-02 19:57 UTC, raphaelwho commented on client/components/related/Card.jsx
> +  componentDidMount() {
You are right. But again. this is just a sketch of the related part.  I agree we should make a helper file to make the work more clean.

2021-06-02 23:05 UTC, minongcopper commented
Hello @raphaelwho and @ahamilton454!

I have reviewed this PR and comments and I feel like you're both headed in the right direction. Is there any way we can mock these components in index.jsx before proceeding forward? I see the import at the top of index.jsx for Square_button, but I don't see index rendering the button anywhere. I spent a few minutes trying to patch it together myself, but I'm getting a ton of Babel and dependency errors.

Regarding organization, I think we're going to get that worked out as a group. I know that what I wrote did not correspond with others' organizational patterns either. We'll work those kinks out!  But great progress!

2021-06-03 01:53 UTC, ahamilton454 requested changes
Use Dummy Data

2021-06-03 02:19 UTC, closed without merging